server:
  port: 8666
# 启动两个eureka，互相注册，实现高可用注册中心
eureka:
  instance:
    hostname: localhost2
    instance-id: eureka-2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost1:8777/eureka/
spring:
  application:
    name: eureka-center