server:
  port: 8787
spring:
  profiles:
    active: dev1
  application:
    name: demo-for-test
  datasource:
    druid:
      filter:
        # Druid slf4j 日志
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
          connection-log-enabled: false
          statement-log-enabled: false
          result-set-log-enabled: false
          statement-executable-sql-log-enable: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, hystrix.stream
# 集成 PostgreSQL 报错：这个 org.postgresql.jdbc.PgConnection.createClob() 方法尚未被实作。
logging:
  level:
    org:
      hibernate:
        engine:
          jdbc:
            env:
              internal:
                LobCreatorBuilderImpl: ERROR
---
spring:
  profiles: dev1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: demo-for-test-1
  client:
    service-url:
      defaultZone: http://localhost1:8777/eureka/,http://localhost2:8666/eureka/
---
server:
  port: 8786
spring:
  profiles: dev2
eureka:
  instance:
    prefer-ip-address: true
    instance-id: demo-for-test-2
  client:
    service-url:
      defaultZone: http://localhost1:8777/eureka/,http://localhost2:8666/eureka/
---
server:
  port: 8785
spring:
  profiles: dev3
eureka:
  instance:
    prefer-ip-address: true
    instance-id: demo-for-test-3
  client:
    service-url:
      defaultZone: http://localhost1:8777/eureka/,http://localhost2:8666/eureka/